# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -cb.phantom@ya.ru
    on_success: never # default: change
    on_failure: always # default: always

    # ключ с сайта https://codecov.io
    env:
    global:
      - CODECOV_TOKEN="7a39ffb2-5b96-46b2-ba7d-9454183afca7"